### ISSUE TITLE
Ensimmäiset testit olemassa olevalle

### ISSUE THREAD

**Issue by JoakimJoensuu** [kordaniel/Ohtuprojekti-kesa2020#6]

**Comment by kordaniel** [comment]
Testattavaa koodia ei oikein vielä ole, niin loin uuden moduulin(? eli tuo module_totest) yksikkötestien testaamista varten. Testit sijaitsevat tests-kansiossa. Jonkunlainen gradlen tyyppinen alusta pitäisi varmaan vielä lisätä. Tärkeää olisi, että saataisiin kaikki toimimaan yhdessä CircleCIn kanssa myös.
