### ISSUE TITLE
Abstraktoi kamera

### ISSUE THREAD

**Issue by JoakimJoensuu** [kordaniel/Ohtuprojekti-kesa2020#7]

**Comment by kordaniel** [comment]
Hyvältä näyttää, helppo lähteä laajentamaan tarpeen mukaan sitten. Pythonin docstringit vissiin eroavat vähän javan tyylistä: https://www.python.org/dev/peps/pep-0257/ eli varmaan pitäisi siirtää ne metodien sisälle?

**Comment by Teo44** [comment]
Docstringit korjattu
